name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttihp25b
        with:
          pdk: ihp

      - name: Create and publish the GDS artifact
        uses: actions/upload-artifact@v4
        with:
          name: gds_render
          path: runs/*/results/gds/*.gds   # ✅ fixed: proper GDS output location

      - name: List files after GDS run
        run: ls -R runs || true

      - name: Upload Viewer Files
        uses: actions/upload-artifact@v4
        with:
          name: viewer
          path: runs/*/results/            # ✅ fixed: upload viewer files correctly
