name: LVS Check

on:
  push:
  workflow_dispatch:

jobs:
  lvs:
    runs-on: ubuntu-24.04
    container:
      image: efabless/openlane:latest   # Prebuilt container with Sky130 PDK & tools
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set Environment
        run: |
          export PDK_ROOT=/opt/pdk
          echo "PDK_ROOT=$PDK_ROOT" >> $GITHUB_ENV
          echo "Using PDK_ROOT=$PDK_ROOT"

      - name: Run LVS with Netgen
        run: |
          cd $GITHUB_WORKSPACE
          echo "Running LVS check..."
          netgen -batch lvs "layout.spice layout" "schematic.spice schematic" $PDK_ROOT/sky130A/libs.tech/netgen/sky130A_setup.tcl
